title: Andrew Rogers
logo: assests/img/headshot_circle.jpg
description: <a href="https://www.linkedin.com/in/andrew~rogers/">View My LinkedIn Profile</a> 
show_downloads: false
theme: jekyll-theme-minimal
